default_stages: [commit]
repos:
  - repo: https://github.com/yyang-even/yyLinuxConfig
    rev: e475e920fedb28f7bff2a58d1142a255fd3e86c4
    hooks:
      - id: astyle-c
      - id: astyle-cpp
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        stages: [commit]
